spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:exchanges
    driver-class-name: org.h2.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
